# Generated by Django 3.0a1 on 2019-12-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20191007_0112'),
    ]

    operations = [
    ]

